spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///beyoung?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: wangjil
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true

user:
  address.max-count: 20

logging:
  level:
    per.poacher: debug
